# Multi-Toolkit Configuration
# Demonstrates combining multiple toolkits for complex tasks

agents:
  executor:
    llm:
      model: openai/gpt-4o
      temperature: 0.4
      max_tokens: 4000
    prediction_strategy: react
    toolkits:
      # Code execution
      - class_name: E2BToolkit
        enabled: true
        toolkit_config:
          timeout: 600
          auto_reinitialize: true

      # File operations
      - class_name: FileToolkit
        enabled: true
        toolkit_config:
          enable_delete: false
          max_file_size: 10485760  # 10MB

      # Math calculations
      - class_name: CalculatorToolkit
        enabled: true

runtime:
  max_depth: 5
  timeout: 1800
  enable_logging: true

# Key Concept: Multiple toolkits work together
# - E2B for code execution
# - FileToolkit for local file I/O
# - CalculatorToolkit for math operations

# Usage:
#   uv run python -m roma_dspy.cli solve "Generate a Python script that calculates fibonacci numbers, execute it, and save results to file" --config config/examples/basic/multi_toolkit.yaml